name: "Website change monitor action"
description: "Monitors the contents of a website and sends you a notification whenever it changes."
runs:
    using: "node20"
    main: "dist/index.js"
inputs:
    url:
        description: "The URL to monitor"
        required: true
    selector:
        description: "The CSS selector to narrow down the content to monitor"
        required: false
    discord-webhook-url:
        description: "The Discord webhook URL to send notifications to"
        required: false
    slack-webhook-url:
        description: "The Slack webhook URL to send notifications to"
        required: false
